services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8080:3000
    restart: always
    volumes:
      - ./:/elections-issues
      - /elections-issues/node_modules
    networks:
      - election_issues_network

networks:
  election_issues_network:
    external: true
