/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    DrawerMenu: typeof import('./components/DrawerMenu.vue')['default']
    FooterMenu: typeof import('./components/FooterMenu.vue')['default']
    HeaderMenu: typeof import('./components/HeaderMenu.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
